# Generated by Django 3.2.5 on 2021-07-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150, null=True)),
                ('lname', models.CharField(max_length=150, null=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('fm', 'Female'), ('o', 'Others')], max_length=2, null=True)),
                ('department', models.CharField(max_length=150, null=True)),
                ('hospital', models.CharField(max_length=150, null=True)),
                ('date', models.DateTimeField()),
                ('time', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
