# Generated by Django 3.2.5 on 2021-07-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150, null=True)),
                ('lname', models.CharField(max_length=150, null=True)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('mname', models.CharField(max_length=100, null=True)),
                ('disease', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
