# Generated by Django 3.2.5 on 2021-07-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
