# Generated by Django 3.2.5 on 2021-07-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20210727_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='mname',
        ),
    ]
