# Generated by Django 3.2.5 on 2021-08-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_hospital_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='hospitals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.hospital'),
        ),
    ]
