# Generated by Django 3.2.5 on 2021-08-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_auto_20210810_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hospitals',
        ),
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
