# Generated by Django 3.2.5 on 2021-08-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_hospital_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash'), ('Khalti', 'Khalti')], default='Cash On Delivery', max_length=20),
        ),
    ]
