# Generated by Django 3.2.5 on 2021-08-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_hospital_hos_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='hos_id',
        ),
    ]
