# Generated by Django 3.2.5 on 2021-08-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_remove_hospital_hos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150, null=True, verbose_name='First Name')),
                ('lname', models.CharField(max_length=150, null=True, verbose_name='Last Name')),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('delivry_add', models.CharField(max_length=200, null=True, verbose_name='Delivery Address')),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('fm', 'Female'), ('o', 'Others')], max_length=2, null=True)),
                ('Age', models.IntegerField()),
                ('Med_name', models.CharField(max_length=200, null=True, verbose_name='Medicine Name')),
                ('m_volume', models.IntegerField(verbose_name='Medicine Volume')),
                ('m_description', models.CharField(max_length=400, null=True, verbose_name='Medicine Description')),
            ],
        ),
    ]
